# Generated by Django 3.2 on 2024-11-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='parts_category',
            field=models.CharField(choices=[('hair', '髪'), ('eyes', '目'), ('clothes', '服'), ('accessory', 'アクセサリー'), ('background', '背景')], max_length=10),
        ),
    ]
